#!/bin/bash


echo $LOAD_FILES | grep -q "$(realpath ${BASH_SOURCE[0]})" && return
LOAD_FILES="$(realpath ${BASH_SOURCE[0]})":$LOAD_FILES

. $(dirname $(realpath ${BASH_SOURCE[0]}))/config/global

. $PATH_LIBS/colors
. $PATH_LIBS/log
