#!/bin/sh

# MONITOR_LIB_FILES
echo $MONITOR_LIB_FILES | grep -q "$(realpath ${BASH_SOURCE[0]})" && return
export MONITOR_LIB_FILES="$(realpath ${BASH_SOURCE[0]})":$MONITOR_LIB_FILES

. $(dirname $(dirname $(realpath ${BASH_SOURCE[0]})))/config/global

. $LIBS_PATH/colors
. $LIBS_PATH/log
. $LIBS_DB_SH_PATH/mysql

exec 1>>$MAIN_LOG 2>&1

