#!/bin/bash

PATH_MAIN=$(git rev-parse --show-toplevel 2>/dev/null || dirname $(dirname $(realpath ${BASH_SOURCE[0]})))
. $PATH_MAIN/sbin/load

repos_path=$1
for user in 'angus_robot@163.com'
do
    echo $user:
    for repo in $(findGitRepo $repos_path)
    do
        cd $repo
        res=(`git log --author="$user" --pretty=tformat: --numstat | gawk '{add += $1; subs += $2; loc += $1 - $2} END {printf "%s +%s -%s\n",loc,add,subs}'`)
        [ "${#res[@]}" -eq 0 ] && continue
        echo -e "  $repo:\t${res[@]}"
    done
done
