#!/bin/sh
#
# https://docs.opencv.org/master/dd/dd5/tutorial_py_setup_in_fedora.html
set -e

dnf install numpy opencv*

# test
# import cv2 as cv
# print( cv.__version__ )

dnf install -y cmake
dnf install -y python-devel numpy
dnf install -y gcc gcc-c++

dnf install -y gtk2-devel
dnf install -y libdc1394-devel
dnf install -y ffmpeg-devel
dnf install -y gstreamer1-plugins-base-devel

dnf install -y libpng-devel
dnf install -y libjpeg-turbo-devel
dnf install -y jasper-devel
dnf install -y openexr-devel
dnf install -y libtiff-devel
dnf install -y libwebp-devel

dnf install -y tbb-devel

dnf install -y eigen3-devel

dnf install -y doxygen

dnf install git
git clone --recurse-submodules https://github.com/opencv/opencv.git

cd opencv
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D BUILD_DOCS=ON \
      ..

make
#make install

