#!/bin/sh
set -e
# Used for fedora 33 x86_64 machine

# install repo
wget https://repo.mysql.com//mysql80-community-release-fc33-1.noarch.rpm
dnf install -y mysql80-community-release-fc33-1.noarch.rpm
dnf config-manager --enable mysql80-community

# install mysql-server-suite
dnf install -y mysql-community-server
systemctl start mysqld.service
systemctl status mysqld.service

# workbench
dnf install -y mysql-workbench-community-8.0.22-1.fc33.x86_64

