#!/bin/sh


PATH_MAIN=$(git rev-parse --show-toplevel 2>/dev/null)
PATH_CONFIG=$PATH_MAIN/config
PATH_LIBS=$PATH_MAIN/libs
PATH_LIBS_DB=$LIBS_PATH/db
PATH_LOGS=$PATH_MAIN/logs
PATH_OSINFO=$PATH_MAIN/os-info
PATH_SBIN=$PATH_MAIN/sbin

FILE_LOG=$PATH_LOGS/all.log
