#!/bin/bash

timestamp() {
    echo $(date +"%Y-%m-%d %H:%M:%S")
}

DEBUG() {
    if [ -n "$FILE_LOG" ] ;then
        [ -f $PATH_LOGS/$FILE_LOG ] || > $PATH_LOGS/$FILE_LOG
        echo -e "[$(timestamp)] ${CYAN}[DEBUG] $@${WHITE}" | tee -a $PATH_LOGS/$FILE_LOG
    else
        echo -e "[$(timestamp)] ${CYAN}[DEBUG] $@${WHITE}"
    fi
}

INFO() {
    if [ -n "$FILE_LOG" ] ;then
        [ -f $PATH_LOGS/$FILE_LOG ] || > $PATH_LOGS/$FILE_LOG
        echo -e "[$(timestamp)] ${GREEN}[INFO] $@${WHITE}" | tee -a $PATH_LOGS/$FILE_LOG
    else
        echo -e "[$(timestamp)] ${GREEN}[INFO] $@${WHITE}"
    fi
}

WARN() {
    if [ -n "$FILE_LOG" ] ;then
        [ -f $PATH_LOGS/$FILE_LOG ] || > $PATH_LOGS/$FILE_LOG
        echo -e "[$(timestamp)] ${YELLOW}[WARN] $@${WHITE}" | tee -a $PATH_LOGS/$FILE_LOG
    else
        echo -e "[$(timestamp)] ${YELLOW}[WARN] $@${WHITE}"
    fi
}

ERROR() {
    if [ -n "$FILE_LOG" ] ;then
        [ -f $PATH_LOGS/$FILE_LOG ] || > $PATH_LOGS/$FILE_LOG
        echo -e "[$(timestamp)] ${RED}[ERROR] $@${WHITE}" | tee -a $PATH_LOGS/$FILE_LOG
    else
        echo -e "[$(timestamp)] ${RED}[ERROR] $@${WHITE}"
    fi
}

FATAL() {
    if [ -n "$FILE_LOG" ] ;then
        [ -f $PATH_LOGS/$FILE_LOG ] || > $PATH_LOGS/$FILE_LOG
        echo -e "[$(timestamp)] ${RED}${BOLD}[FATAL] $@${WHITE}" | tee -a $PATH_LOGS/$FILE_LOG
    else
        echo -e "[$(timestamp)] ${RED}${BOLD}[FATAL] $@${WHITE}"
    fi
}
