#!/bin/sh

timestamp() {
    echo $(date +"%Y-%m-%d %H:%M:%S")
}

DEBUG() {
    echo -e \[$(timestamp)\] ${GREEN}\[DEBUG\] ${WHITE}"$*"
}

INFO() {
    echo -e \[$(timestamp)\] ${YELLOW}\[INFO\] ${WHITE}"$*"
}

ERROR() {
    echo -e \[$(timestamp)\] ${RED}\[ERROR\] ${WHITE}"$*"
}

FATAL() {
    echo -e \[$(timestamp)\] ${RED}${BOLD}\[FATAL\] ${WHITE}"$*"
}

